package Bixi.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import java.util.ArrayList;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Dimension;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import javax.swing.JButton;

public class DTown extends JFrame {
  public ArrayList<DTown.Street> streets = new ArrayList<DTown.Street>();
  public ArrayList<DTown.Movement> movements = new ArrayList<DTown.Movement>();
  public ArrayList<DTown.BikeRack> racks = new ArrayList<DTown.BikeRack>();
  public ArrayList<DTown.Member> members = new ArrayList<DTown.Member>();
  public int day = 8;
  public int time = 100;
  public boolean initialized = false;
  public boolean iterate = false;
  public static void main(String[] args) {
    DTown n = new DTown();
    n.initialize();
  }

  public void initialize() {
    streets.add(new DTown.Street("Sherbrooke", 15));
    streets.add(new DTown.Street("Peel", 15));
    members.add(new DTown.Member(12, "Alec"));
    DTown.Street hStreet = null;
    DTown.Street vStreet = null;
    for (DTown.Street s : streets) {
      if ("Sherbrooke".equals(s.name)) {
        hStreet = s;
      }
      if ("Peel".equals(s.name)) {
        vStreet = s;
      }
      try {
        if (!(hStreet.equals(null)) && !(vStreet.equals(null))) {
          racks.add(new DTown.BikeRack(5, 10, 1, hStreet, vStreet));
          hStreet = null;
          vStreet = null;
        }
      } catch (NullPointerException n) {
      }
    }
    for (DTown.Street s : streets) {
      if ("Sherbrooke".equals(s.name)) {
        hStreet = s;
      }
      if ("Peel".equals(s.name)) {
        vStreet = s;
      }
      try {
        if (!(hStreet.equals(null)) && !(vStreet.equals(null))) {
          racks.add(new DTown.BikeRack(4, 20, 3, hStreet, vStreet));
          hStreet = null;
          vStreet = null;
        }
      } catch (NullPointerException n) {
      }
    }
    for (DTown.Street s : streets) {
      if ("Sherbrooke".equals(s.name)) {
        hStreet = s;
      }
      if ("Peel".equals(s.name)) {
        vStreet = s;
      }
      try {
        if (!(hStreet.equals(null)) && !(vStreet.equals(null))) {
          racks.add(new DTown.BikeRack(3, 10, 4, hStreet, vStreet));
          hStreet = null;
          vStreet = null;
        }
      } catch (NullPointerException n) {
      }
    }
    for (DTown.Street s : streets) {
      if ("Sherbrooke".equals(s.name)) {
        hStreet = s;
      }
      if ("Peel".equals(s.name)) {
        vStreet = s;
      }
      try {
        if (!(hStreet.equals(null)) && !(vStreet.equals(null))) {
          racks.add(new DTown.BikeRack(30, 60, 2, hStreet, vStreet));
          hStreet = null;
          vStreet = null;
        }
      } catch (NullPointerException n) {
      }
    }
    DTown.BikeRack source = null;
    DTown.BikeRack target = null;
    DTown.Member member = null;
    boolean movementInserted = false;
    for (DTown.BikeRack r : racks) {
      if (r.hStreet.name.equals("Sherbrooke") && r.vStreet.name.equals("Peel") && r.quadrant == 1) {
        source = r;
      }
      if (r.hStreet.name.equals("Sherbrooke") && r.vStreet.name.equals("Peel") && r.quadrant == 3) {
        target = r;
      }

      for (DTown.Member m : members) {
        if (m.ID == 12) {
          member = m;
        }
        try {
          if (!(source.equals(null)) && !(target.equals(null)) && !(member.equals(null))) {
            movements.add(new DTown.MemberMovement(member, 4, 16, 1, source, target));
            source = null;
            target = null;
            member = null;
            movementInserted = true;
            break;
          }
        } catch (NullPointerException n) {
        }
      }
      if (movementInserted) {
        movementInserted = false;
        break;
      }
    }
    for (DTown.BikeRack r : racks) {
      if (r.hStreet.name.equals("Sherbrooke") && r.vStreet.name.equals("Peel") && r.quadrant == 3) {
        source = r;
      }
      if (r.hStreet.name.equals("Sherbrooke") && r.vStreet.name.equals("Peel") && r.quadrant == 1) {
        target = r;
      }

      try {
        if (!(source.equals(null)) && !(target.equals(null))) {
          movements.add(new DTown.Redistribution(5, 12, 10, source, target));
          source = null;
          target = null;
          member = null;
          movementInserted = true;
          break;
        }
      } catch (NullPointerException n) {
      }
      if (movementInserted) {
        movementInserted = false;
        break;
      }
    }

    for (DTown.Movement m : movements) {
      if (m.dayOfWeek <= day) {
        if (m.timeSlot < time) {
          day = m.dayOfWeek;
          time = m.timeSlot;
        }
      }
    }
    initialized = true;
    panel.repaint();
    this.setTitle("DTown");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    button.setAlignmentX(LEFT_ALIGNMENT);
    button.setAlignmentY(TOP_ALIGNMENT);
    button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent p0) {
        executeMovements();
      }
    });
    panel.add(button);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }

  private JPanel panel = new JPanel() {
    @Override
    public void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      setBackground(Color.WHITE);
      if (!(initialized)) {
        graphics.setColor(Color.black);
        graphics.drawLine(0 * 5, 15 * 5, 100 * 5, 15 * 5);
        graphics.drawString("Sherbrooke", (((0 + 100) / 2) + 2) * 5, (15 + 2) * 5);
        graphics.setColor(Color.black);
        graphics.drawLine(15 * 5, 10 * 5, 15 * 5, 70 * 5);
        graphics.drawString("Peel", (15 + 2) * 5, (((10 + 70) / 2) + 2) * 5);
        graphics.setColor(Color.black);
        if (5 < 0 || 5 > 10) {
          graphics.setColor(Color.red);
        }
        graphics.drawOval((15 + 2) * 5, (15 - 2) * 5, 3, 3);
        graphics.drawString(5 + "/" + 10, (15 + 3) * 5, (15 - 3) * 5);
        graphics.setColor(Color.black);
        if (4 < 0 || 4 > 20) {
          graphics.setColor(Color.red);
        }
        graphics.drawOval((15 - 2) * 5, (15 + 2) * 5, 3, 3);
        graphics.drawString(4 + "/" + 20, (15 - 8) * 5, (15 + 6) * 5);
        graphics.setColor(Color.black);
        if (3 < 0 || 3 > 10) {
          graphics.setColor(Color.red);
        }
        graphics.drawOval((15 + 2) * 5, (15 + 2) * 5, 3, 3);
        graphics.drawString(3 + "/" + 10, (15 + 3) * 5, (15 + 6) * 5);
        graphics.setColor(Color.black);
        if (30 < 0 || 30 > 60) {
          graphics.setColor(Color.red);
        }
        graphics.drawOval((15 - 2) * 5, (15 - 2) * 5, 3, 3);
        graphics.drawString(30 + "/" + 60, (15 - 8) * 5, (15 - 3) * 5);
      }
      if (initialized && !(iterate)) {
        String sDay = "Sunday";
        String sTime = "Evening";
        if (day == 1) {
          sDay = "Monday";
        }
        if (day == 2) {
          sDay = "Tuesday";
        }
        if (day == 3) {
          sDay = "Wednesday";
        }
        if (day == 4) {
          sDay = "Thursday";
        }
        if (day == 5) {
          sDay = "Friday";
        }
        if (day == 6) {
          sDay = "Saturday";
        }
        if (time == 0) {
          sTime = "Night";
        }
        if (time == 4) {
          sTime = "Early Morning";
        }
        if (time == 8) {
          sTime = "Morning";
        }
        if (time == 12) {
          sTime = "Midday";
        }
        if (time == 16) {
          sTime = "Afternoon";
        }
        graphics.drawString(sDay + ", " + sTime, 300, 20);
        graphics.setColor(Color.black);
        graphics.drawLine(0 * 5, 15 * 5, 100 * 5, 15 * 5);
        graphics.drawString("Sherbrooke", (((0 + 100) / 2) + 2) * 5, (15 + 2) * 5);
        graphics.setColor(Color.black);
        graphics.drawLine(15 * 5, 10 * 5, 15 * 5, 70 * 5);
        graphics.drawString("Peel", (15 + 2) * 5, (((10 + 70) / 2) + 2) * 5);
        graphics.setColor(Color.black);
        if (5 < 0 || 5 > 10) {
          graphics.setColor(Color.red);
        }
        graphics.drawOval((15 + 2) * 5, (15 - 2) * 5, 3, 3);
        graphics.drawString(5 + "/" + 10, (15 + 3) * 5, (15 - 3) * 5);
        graphics.setColor(Color.black);
        if (4 < 0 || 4 > 20) {
          graphics.setColor(Color.red);
        }
        graphics.drawOval((15 - 2) * 5, (15 + 2) * 5, 3, 3);
        graphics.drawString(4 + "/" + 20, (15 - 8) * 5, (15 + 6) * 5);
        graphics.setColor(Color.black);
        if (3 < 0 || 3 > 10) {
          graphics.setColor(Color.red);
        }
        graphics.drawOval((15 + 2) * 5, (15 + 2) * 5, 3, 3);
        graphics.drawString(3 + "/" + 10, (15 + 3) * 5, (15 + 6) * 5);
        graphics.setColor(Color.black);
        if (30 < 0 || 30 > 60) {
          graphics.setColor(Color.red);
        }
        graphics.drawOval((15 - 2) * 5, (15 - 2) * 5, 3, 3);
        graphics.drawString(30 + "/" + 60, (15 - 8) * 5, (15 - 3) * 5);
      }
      if (initialized && iterate) {
        graphics.setColor(Color.black);
        graphics.drawLine(0 * 5, 15 * 5, 100 * 5, 15 * 5);
        graphics.drawString("Sherbrooke", (((0 + 100) / 2) + 2) * 5, (15 + 2) * 5);
        graphics.setColor(Color.black);
        graphics.drawLine(15 * 5, 10 * 5, 15 * 5, 70 * 5);
        graphics.drawString("Peel", (15 + 2) * 5, (((10 + 70) / 2) + 2) * 5);
        for (DTown.BikeRack r : racks) {
          graphics.setColor(Color.black);
          if (r.quadrant == 1) {
            if (r.numberOfBikes < 0 || r.numberOfBikes > r.limit) {
              graphics.setColor(Color.red);
            }
            graphics.drawOval((r.vStreet.placement + 2) * 5, (r.hStreet.placement - 2) * 5, 3, 3);
            graphics.drawString(r.numberOfBikes + "/" + r.limit, (r.vStreet.placement + 3) * 5, (r.hStreet.placement - 3) * 5);
          }
          if (r.quadrant == 2) {
            if (r.numberOfBikes < 0 || r.numberOfBikes > r.limit) {
              graphics.setColor(Color.red);
            }
            graphics.drawOval((r.vStreet.placement - 2) * 5, (r.hStreet.placement - 2) * 5, 3, 3);
            graphics.drawString(r.numberOfBikes + "/" + r.limit, (r.vStreet.placement - 8) * 5, (r.hStreet.placement - 3) * 5);
          }
          if (r.quadrant == 3) {
            if (r.numberOfBikes < 0 || r.numberOfBikes > r.limit) {
              graphics.setColor(Color.red);
            }
            graphics.drawOval((r.vStreet.placement - 2) * 5, (r.hStreet.placement + 2) * 5, 3, 3);
            graphics.drawString(r.numberOfBikes + "/" + r.limit, (r.vStreet.placement - 8) * 5, (r.hStreet.placement + 6) * 5);
          }
          if (r.quadrant == 4) {
            if (r.numberOfBikes < 0 || r.numberOfBikes > r.limit) {
              graphics.setColor(Color.red);
            }
            graphics.drawOval((r.vStreet.placement + 2) * 5, (r.hStreet.placement + 2) * 5, 3, 3);
            graphics.drawString(r.numberOfBikes + "/" + r.limit, (r.vStreet.placement + 3) * 5, (r.hStreet.placement + 6) * 5);

          }
          String sDay = "Sunday";
          String sTime = "Evening";
          if (day == 1) {
            sDay = "Monday";
          }
          if (day == 2) {
            sDay = "Tuesday";
          }
          if (day == 3) {
            sDay = "Wednesday";
          }
          if (day == 4) {
            sDay = "Thursday";
          }
          if (day == 5) {
            sDay = "Friday";
          }
          if (day == 6) {
            sDay = "Saturday";
          }
          if (time == 0) {
            sTime = "Night";
          }
          if (time == 4) {
            sTime = "Early Morning";
          }
          if (time == 8) {
            sTime = "Morning";
          }
          if (time == 12) {
            sTime = "Midday";
          }
          if (time == 16) {
            sTime = "Afternoon";
          }
          graphics.drawString(sDay + ", " + sTime, 300, 20);
        }
      }
    }
  };

  private JButton button = new JButton("Next");

  private ActionEvent executeMovements() {
    iterate = true;
    for (DTown.Movement m : movements) {
      if (m.dayOfWeek == day && m.timeSlot == time) {
        if (m instanceof DTown.MemberMovement) {
          m.source.numberOfBikes = m.source.numberOfBikes - m.numberOfBikes;
          m.target.numberOfBikes = m.target.numberOfBikes + m.numberOfBikes;
        }
        if (m instanceof DTown.Redistribution) {
          m.source.numberOfBikes = m.source.numberOfBikes - m.numberOfBikes;
          m.target.numberOfBikes = m.target.numberOfBikes + m.numberOfBikes;
        }
        if (m instanceof DTown.RandomMovement) {
          double upper = m.numberOfBikes * 1.5;
          double lower = m.numberOfBikes * 0.5;
          double diff = upper - lower;
          int ran = (int) ((Math.random() * diff) + lower);
          m.source.numberOfBikes = m.source.numberOfBikes - ran;
          m.target.numberOfBikes = m.target.numberOfBikes + ran;

        }
      }
    }
    panel.repaint();
    resetTime();
    return null;
  }

  public void resetTime() {
    int currDay = nextDay();
    boolean sameDay = false;
    if (currDay == day) {
      sameDay = true;
    }
    day = currDay;
    time = nextTimeSlot(sameDay);
  }
  public int nextDay() {
    for (int i = day; i <= 7; i++) {
      for (DTown.Movement m : movements) {
        if (m.dayOfWeek == day && m.timeSlot > time) {
          return i;
        }
        if (m.dayOfWeek == i && i > day) {
          return i;
        }
      }
    }
    return 7;
  }
  public int nextTimeSlot(boolean sameDay) {
    if (sameDay) {
      for (int i = time + 4; i <= 20; i = i + 4) {
        for (DTown.Movement m : movements) {
          if (m.dayOfWeek == day && m.timeSlot == i) {
            return i;
          }
        }
      }
    }
    if (!(sameDay)) {
      for (int i = day; i <= 7; i++) {
        for (int j = 0; j <= 20; j = j + 4) {
          for (DTown.Movement m : movements) {
            if (m.dayOfWeek == i && m.timeSlot == j) {
              return j;
            }
          }
        }
      }
    }
    return 20;
  }

  private class Member {
    public int ID;
    public String name;
    public Member(int pID, String pName) {
      this.ID = pID;
      this.name = pName;
    }
  }
  private abstract class Movement {
    public int dayOfWeek;
    public int timeSlot;
    public int numberOfBikes;
    public DTown.BikeRack target;
    public DTown.BikeRack source;
  }
  private class MemberMovement extends DTown.Movement {
    public DTown.Member member;
    public MemberMovement(DTown.Member pM, int pDay, int pTime, int pNum, DTown.BikeRack pSource, DTown.BikeRack pTarget) {
      this.member = pM;
      this.dayOfWeek = pDay;
      this.timeSlot = pTime;
      this.numberOfBikes = pNum;
      this.target = pTarget;
      this.source = pSource;
    }

  }
  private class RandomMovement extends DTown.Movement {
    private RandomMovement(int pDay, int pTime, int pNum, DTown.BikeRack pSource, DTown.BikeRack pTarget) {
      this.dayOfWeek = pDay;
      this.timeSlot = pTime;
      this.numberOfBikes = pNum;
      this.source = pSource;
      this.target = pTarget;
    }

  }
  private class Redistribution extends DTown.Movement {
    private Redistribution(int pDay, int pTime, int pNum, DTown.BikeRack pSource, DTown.BikeRack pTarget) {
      this.dayOfWeek = pDay;
      this.timeSlot = pTime;
      this.numberOfBikes = pNum;
      this.source = pSource;
      this.target = pTarget;
    }
  }
  private class BikeRack {
    public int numberOfBikes;
    public int limit;
    public int quadrant;
    public DTown.Street hStreet;
    public DTown.Street vStreet;
    public BikeRack(int pNum, int pLim, int pQuad, DTown.Street pH, DTown.Street pV) {
      this.numberOfBikes = pNum;
      this.limit = pLim;
      this.quadrant = pQuad;
      this.hStreet = pH;
      this.vStreet = pV;
    }
  }
  private class Street {
    public String name;
    public int placement;
    public Street(String pName, int pPlace) {
      this.name = pName;
      this.placement = pPlace;
    }
  }

}
