package Bixi.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myBikeRack__BehaviorDescriptor = new BikeRack__BehaviorDescriptor();
  private final BHDescriptor myHorizontalStreet__BehaviorDescriptor = new HorizontalStreet__BehaviorDescriptor();
  private final BHDescriptor myMember__BehaviorDescriptor = new Member__BehaviorDescriptor();
  private final BHDescriptor myMemberMovement__BehaviorDescriptor = new MemberMovement__BehaviorDescriptor();
  private final BHDescriptor myMovement__BehaviorDescriptor = new Movement__BehaviorDescriptor();
  private final BHDescriptor myNeighbourhood__BehaviorDescriptor = new Neighbourhood__BehaviorDescriptor();
  private final BHDescriptor myRandomMovement__BehaviorDescriptor = new RandomMovement__BehaviorDescriptor();
  private final BHDescriptor myRedistribution__BehaviorDescriptor = new Redistribution__BehaviorDescriptor();
  private final BHDescriptor myStreet__BehaviorDescriptor = new Street__BehaviorDescriptor();
  private final BHDescriptor myVerticalStreet__BehaviorDescriptor = new VerticalStreet__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myBikeRack__BehaviorDescriptor;
      case 1:
        return myHorizontalStreet__BehaviorDescriptor;
      case 2:
        return myMember__BehaviorDescriptor;
      case 3:
        return myMemberMovement__BehaviorDescriptor;
      case 4:
        return myMovement__BehaviorDescriptor;
      case 5:
        return myNeighbourhood__BehaviorDescriptor;
      case 6:
        return myRandomMovement__BehaviorDescriptor;
      case 7:
        return myRedistribution__BehaviorDescriptor;
      case 8:
        return myStreet__BehaviorDescriptor;
      case 9:
        return myVerticalStreet__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696800L), MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696801L), MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696802L), MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696803L), MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696804L), MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696805L), MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696808L), MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696809L), MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e269680aL), MetaIdFactory.conceptId(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e269680bL)).seal();
}
