package Bixi.behavior;

/*Generated by MPS */

import javax.swing.JPanel;
import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import java.awt.Dimension;
import java.awt.Graphics;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.IVisitor;

public final class PreviewFactory {

  public static JPanel createPanel(final SNode n) {
    return new JPanel() {
      @Override
      public Border getBorder() {
        return new TitledBorder("Neighbourhood");
      }
      @Override
      public Dimension getPreferredSize() {
        return new Dimension(500, 500);
      }
      protected void paintComponent(final Graphics g) {
        super.paintComponent(g);
        SNodeOperations.getModel(n).getRepository().getModelAccess().runReadAction(new Runnable() {
          public void run() {
            ListSequence.fromList(SLinkOperations.getChildren(n, MetaAdapterFactory.getContainmentLink(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696805L, 0x6be7fb71e269683eL, "streets"))).visitAll(new IVisitor<SNode>() {
              public void visit(SNode it) {
                Street__BehaviorDescriptor.drawStreet_id25yLi$WpTCj.invoke(it, g);
              }
            });
          }
        });
        SNodeOperations.getModel(n).getRepository().getModelAccess().runReadAction(new Runnable() {
          public void run() {
            ListSequence.fromList(SLinkOperations.getChildren(n, MetaAdapterFactory.getContainmentLink(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696805L, 0x6be7fb71e2696840L, "racks"))).visitAll(new IVisitor<SNode>() {
              public void visit(SNode it) {
                BikeRack__BehaviorDescriptor.drawRack_id7gwM88jgyxB.invoke(it, g);
              }
            });
          }
        });
      }
    };
  }


}
