package Bixi.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseConstraintsAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class ConstraintsAspectDescriptor extends BaseConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }

  @Override
  public ConstraintsDescriptor getConstraints(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return new BikeRack_Constraints();
      case 1:
        return new Member_Constraints();
      case 2:
        return new MemberMovement_Constraints();
      case 3:
        return new Movement_Constraints();
      case 4:
        return new Neighbourhood_Constraints();
      case 5:
        return new RandomMovement_Constraints();
      case 6:
        return new Redistribution_Constraints();
      case 7:
        return new Street_Constraints();
      default:
    }
    return new BaseConstraintsDescriptor(concept);
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x80abab196e2b414aL, 0xbf443232f0a94d40L, 0x32f20c5cdebdfb51L), MetaIdFactory.conceptId(0x80abab196e2b414aL, 0xbf443232f0a94d40L, 0x3663fa1ece76bc9cL), MetaIdFactory.conceptId(0x80abab196e2b414aL, 0xbf443232f0a94d40L, 0x3663fa1ece76bca1L), MetaIdFactory.conceptId(0x80abab196e2b414aL, 0xbf443232f0a94d40L, 0x3663fa1ece76bf33L), MetaIdFactory.conceptId(0x80abab196e2b414aL, 0xbf443232f0a94d40L, 0x32f20c5cdebdea86L), MetaIdFactory.conceptId(0x80abab196e2b414aL, 0xbf443232f0a94d40L, 0x3663fa1ece76bbd1L), MetaIdFactory.conceptId(0x80abab196e2b414aL, 0xbf443232f0a94d40L, 0x3663fa1ece76bbd2L), MetaIdFactory.conceptId(0x80abab196e2b414aL, 0xbf443232f0a94d40L, 0x32f20c5cdebdeafbL)).seal();
}
