package Bixi.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BikeRack = 0;
  public static final int Member = 1;
  public static final int MemberMovement = 2;
  public static final int Movement = 3;
  public static final int Neighbourhood = 4;
  public static final int RandomMovement = 5;
  public static final int Redistribution = 6;
  public static final int Street = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x80abab196e2b414aL, 0xbf443232f0a94d40L);
    builder.put(0x32f20c5cdebdfb51L, BikeRack);
    builder.put(0x3663fa1ece76bc9cL, Member);
    builder.put(0x3663fa1ece76bca1L, MemberMovement);
    builder.put(0x3663fa1ece76bf33L, Movement);
    builder.put(0x32f20c5cdebdea86L, Neighbourhood);
    builder.put(0x3663fa1ece76bbd1L, RandomMovement);
    builder.put(0x3663fa1ece76bbd2L, Redistribution);
    builder.put(0x32f20c5cdebdeafbL, Street);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
