package Bixi.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BikeRack = 0;
  public static final int HorizontalStreet = 1;
  public static final int Member = 2;
  public static final int MemberMovement = 3;
  public static final int Movement = 4;
  public static final int Neighbourhood = 5;
  public static final int RandomMovement = 6;
  public static final int Redistribution = 7;
  public static final int Street = 8;
  public static final int VerticalStreet = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L);
    builder.put(0x6be7fb71e2696800L, BikeRack);
    builder.put(0x6be7fb71e2696801L, HorizontalStreet);
    builder.put(0x6be7fb71e2696802L, Member);
    builder.put(0x6be7fb71e2696803L, MemberMovement);
    builder.put(0x6be7fb71e2696804L, Movement);
    builder.put(0x6be7fb71e2696805L, Neighbourhood);
    builder.put(0x6be7fb71e2696808L, RandomMovement);
    builder.put(0x6be7fb71e2696809L, Redistribution);
    builder.put(0x6be7fb71e269680aL, Street);
    builder.put(0x6be7fb71e269680bL, VerticalStreet);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
