package Bixi.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Quadrant {
  _1("tr", 1),
  _2("tl", 2),
  _3("bl", 3),
  _4("br", 4);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  Quadrant(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<Quadrant> getConstants() {
    List<Quadrant> list = ListSequence.fromList(new LinkedList<Quadrant>());
    ListSequence.fromList(list).addElement(Quadrant._1);
    ListSequence.fromList(list).addElement(Quadrant._2);
    ListSequence.fromList(list).addElement(Quadrant._3);
    ListSequence.fromList(list).addElement(Quadrant._4);
    return list;
  }
  public static Quadrant getDefault() {
    return Quadrant._1;
  }
  public static Quadrant parseValue(String value) {
    if (value == null) {
      return Quadrant.getDefault();
    }
    if (value.equals(Quadrant._1.getValueAsString())) {
      return Quadrant._1;
    }
    if (value.equals(Quadrant._2.getValueAsString())) {
      return Quadrant._2;
    }
    if (value.equals(Quadrant._3.getValueAsString())) {
      return Quadrant._3;
    }
    if (value.equals(Quadrant._4.getValueAsString())) {
      return Quadrant._4;
    }
    return Quadrant.getDefault();
  }
}
