package Bixi.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum StreetOrientation {
  vertical("Vertical", "vertical"),
  horizontal("Horizontal", "horizontal");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private StreetOrientation(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<StreetOrientation> getConstants() {
    List<StreetOrientation> list = ListSequence.fromList(new LinkedList<StreetOrientation>());
    ListSequence.fromList(list).addElement(StreetOrientation.vertical);
    ListSequence.fromList(list).addElement(StreetOrientation.horizontal);
    return list;
  }
  public static StreetOrientation getDefault() {
    return null;
  }
  public static StreetOrientation parseValue(String value) {
    if (value == null) {
      return StreetOrientation.getDefault();
    }
    if (value.equals(StreetOrientation.vertical.getValueAsString())) {
      return StreetOrientation.vertical;
    }
    if (value.equals(StreetOrientation.horizontal.getValueAsString())) {
      return StreetOrientation.horizontal;
    }
    return StreetOrientation.getDefault();
  }
}
