package Bixi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBikeRack = createDescriptorForBikeRack();
  /*package*/ final ConceptDescriptor myConceptHorizontalStreet = createDescriptorForHorizontalStreet();
  /*package*/ final ConceptDescriptor myConceptMember = createDescriptorForMember();
  /*package*/ final ConceptDescriptor myConceptMemberMovement = createDescriptorForMemberMovement();
  /*package*/ final ConceptDescriptor myConceptMovement = createDescriptorForMovement();
  /*package*/ final ConceptDescriptor myConceptNeighbourhood = createDescriptorForNeighbourhood();
  /*package*/ final ConceptDescriptor myConceptRandomMovement = createDescriptorForRandomMovement();
  /*package*/ final ConceptDescriptor myConceptRedistribution = createDescriptorForRedistribution();
  /*package*/ final ConceptDescriptor myConceptStreet = createDescriptorForStreet();
  /*package*/ final ConceptDescriptor myConceptVerticalStreet = createDescriptorForVerticalStreet();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBikeRack, myConceptHorizontalStreet, myConceptMember, myConceptMemberMovement, myConceptMovement, myConceptNeighbourhood, myConceptRandomMovement, myConceptRedistribution, myConceptStreet, myConceptVerticalStreet);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BikeRack:
        return myConceptBikeRack;
      case LanguageConceptSwitch.HorizontalStreet:
        return myConceptHorizontalStreet;
      case LanguageConceptSwitch.Member:
        return myConceptMember;
      case LanguageConceptSwitch.MemberMovement:
        return myConceptMemberMovement;
      case LanguageConceptSwitch.Movement:
        return myConceptMovement;
      case LanguageConceptSwitch.Neighbourhood:
        return myConceptNeighbourhood;
      case LanguageConceptSwitch.RandomMovement:
        return myConceptRandomMovement;
      case LanguageConceptSwitch.Redistribution:
        return myConceptRedistribution;
      case LanguageConceptSwitch.Street:
        return myConceptStreet;
      case LanguageConceptSwitch.VerticalStreet:
        return myConceptVerticalStreet;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBikeRack() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "BikeRack", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696800L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885632");
    b.version(2);
    b.prop("numberOfBikes", 0x6be7fb71e2696812L, "7775459748226885650");
    b.prop("upperLimit", 0x6be7fb71e2696814L, "7775459748226885652");
    b.prop("quadrant", 0x6be7fb71e2696817L, "7775459748226885655");
    b.associate("horizontalStreet", 0x6be7fb71e269681bL).target(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696801L).optional(false).origin("7775459748226885659").done();
    b.associate("verticalStreet", 0x6be7fb71e269681dL).target(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e269680bL).optional(false).origin("7775459748226885661").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHorizontalStreet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "HorizontalStreet", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696801L);
    b.class_(false, false, false);
    b.super_("Bixi.structure.Street", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e269680aL);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885633");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMember() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "Member", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696802L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885634");
    b.version(2);
    b.prop("ID", 0x6be7fb71e2696822L, "7775459748226885666");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMemberMovement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "MemberMovement", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696803L);
    b.class_(false, false, false);
    b.super_("Bixi.structure.Movement", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696804L);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885635");
    b.version(2);
    b.associate("member", 0x6be7fb71e2696824L).target(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696802L).optional(false).origin("7775459748226885668").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMovement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "Movement", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696804L);
    b.class_(false, true, false);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885636");
    b.version(2);
    b.prop("dayOfWeek", 0x6be7fb71e2696826L, "7775459748226885670");
    b.prop("timeslot", 0x6be7fb71e2696828L, "7775459748226885672");
    b.prop("numberOfBikes", 0x6be7fb71e269682bL, "7775459748226885675");
    b.associate("sourceRack", 0x6be7fb71e269682fL).target(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696800L).optional(false).origin("7775459748226885679").done();
    b.associate("targetRack", 0x6be7fb71e2696831L).target(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696800L).optional(false).origin("7775459748226885681").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNeighbourhood() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "Neighbourhood", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696805L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885637");
    b.version(2);
    b.aggregate("streets", 0x6be7fb71e269683eL).target(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e269680aL).optional(true).ordered(true).multiple(true).origin("7775459748226885694").done();
    b.aggregate("racks", 0x6be7fb71e2696840L).target(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696800L).optional(true).ordered(true).multiple(true).origin("7775459748226885696").done();
    b.aggregate("members", 0x6be7fb71e2696843L).target(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696802L).optional(true).ordered(true).multiple(true).origin("7775459748226885699").done();
    b.aggregate("movement", 0x6be7fb71e2696847L).target(0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696804L).optional(true).ordered(true).multiple(true).origin("7775459748226885703").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRandomMovement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "RandomMovement", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696808L);
    b.class_(false, false, false);
    b.super_("Bixi.structure.Movement", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696804L);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885640");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRedistribution() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "Redistribution", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696809L);
    b.class_(false, false, false);
    b.super_("Bixi.structure.Movement", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e2696804L);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885641");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStreet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "Street", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e269680aL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885642");
    b.version(2);
    b.prop("lowerLimit", 0x6be7fb71e2696868L, "7775459748226885736");
    b.prop("upperLimit", 0x6be7fb71e269686aL, "7775459748226885738");
    b.prop("placement", 0x6be7fb71e269686dL, "7775459748226885741");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVerticalStreet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Bixi", "VerticalStreet", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e269680bL);
    b.class_(false, false, false);
    b.super_("Bixi.structure.Street", 0xbf0cd3e1a3fa4f85L, 0xbf1d1f19f9461b19L, 0x6be7fb71e269680aL);
    b.origin("r:68253c69-86bf-466a-ad09-51c632045283(Bixi.structure)/7775459748226885643");
    b.version(2);
    return b.create();
  }
}
