package Bixi.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum TimeSlot {
  _0("Night", 0),
  _4("Early Morning", 4),
  _8("Morning", 8),
  _12("Midday", 12),
  _16("Afternoon", 16),
  _20("Evening", 20);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  TimeSlot(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<TimeSlot> getConstants() {
    List<TimeSlot> list = ListSequence.fromList(new LinkedList<TimeSlot>());
    ListSequence.fromList(list).addElement(TimeSlot._0);
    ListSequence.fromList(list).addElement(TimeSlot._4);
    ListSequence.fromList(list).addElement(TimeSlot._8);
    ListSequence.fromList(list).addElement(TimeSlot._12);
    ListSequence.fromList(list).addElement(TimeSlot._16);
    ListSequence.fromList(list).addElement(TimeSlot._20);
    return list;
  }
  public static TimeSlot getDefault() {
    return null;
  }
  public static TimeSlot parseValue(String value) {
    if (value == null) {
      return TimeSlot.getDefault();
    }
    if (value.equals(TimeSlot._0.getValueAsString())) {
      return TimeSlot._0;
    }
    if (value.equals(TimeSlot._4.getValueAsString())) {
      return TimeSlot._4;
    }
    if (value.equals(TimeSlot._8.getValueAsString())) {
      return TimeSlot._8;
    }
    if (value.equals(TimeSlot._12.getValueAsString())) {
      return TimeSlot._12;
    }
    if (value.equals(TimeSlot._16.getValueAsString())) {
      return TimeSlot._16;
    }
    if (value.equals(TimeSlot._20.getValueAsString())) {
      return TimeSlot._20;
    }
    return TimeSlot.getDefault();
  }
}
