package Bixi.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum WeekDay {
  Monday("Monday", "Monday"),
  Tuesday("Tuesday", "Tuesday"),
  Wednesday("Wednesday", "Wednesday"),
  Thursday("Thursday", "Thursday"),
  Friday("Friday", "Friday"),
  Saturday("Saturday", "Saturday"),
  Sunday("Sunday", "Sunday");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private WeekDay(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<WeekDay> getConstants() {
    List<WeekDay> list = ListSequence.fromList(new LinkedList<WeekDay>());
    ListSequence.fromList(list).addElement(WeekDay.Monday);
    ListSequence.fromList(list).addElement(WeekDay.Tuesday);
    ListSequence.fromList(list).addElement(WeekDay.Wednesday);
    ListSequence.fromList(list).addElement(WeekDay.Thursday);
    ListSequence.fromList(list).addElement(WeekDay.Friday);
    ListSequence.fromList(list).addElement(WeekDay.Saturday);
    ListSequence.fromList(list).addElement(WeekDay.Sunday);
    return list;
  }
  public static WeekDay getDefault() {
    return null;
  }
  public static WeekDay parseValue(String value) {
    if (value == null) {
      return WeekDay.getDefault();
    }
    if (value.equals(WeekDay.Monday.getValueAsString())) {
      return WeekDay.Monday;
    }
    if (value.equals(WeekDay.Tuesday.getValueAsString())) {
      return WeekDay.Tuesday;
    }
    if (value.equals(WeekDay.Wednesday.getValueAsString())) {
      return WeekDay.Wednesday;
    }
    if (value.equals(WeekDay.Thursday.getValueAsString())) {
      return WeekDay.Thursday;
    }
    if (value.equals(WeekDay.Friday.getValueAsString())) {
      return WeekDay.Friday;
    }
    if (value.equals(WeekDay.Saturday.getValueAsString())) {
      return WeekDay.Saturday;
    }
    if (value.equals(WeekDay.Sunday.getValueAsString())) {
      return WeekDay.Sunday;
    }
    return WeekDay.getDefault();
  }
}
